title: Mohamad Shalaby
#google_analytics:

color_scheme: dark
# Enable or disable heading anchors
heading_anchors: true
#permalink: pretty
sidebar:
  nav: ./
  
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-architect
