title: Mohamad Shalaby
 

#description: Cayman is a clean, responsive theme for GitHub Pages.
#show_downloads: true
#google_analytics:
email: mshalaby@live.ca

color_scheme: dark

 
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-architect

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - Research.md
  - Pub.md

