title: Mohamad Shalaby
#description: Cayman is a clean, responsive theme for GitHub Pages.
#show_downloads: true
#google_analytics:

header_pages:
  - index.md  
  - Research.md
  
  
theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky

