title: Mohamad Shalaby
topnav_title: Mohamad Shalaby

#description: Cayman is a clean, responsive theme for GitHub Pages.
#show_downloads: true
#google_analytics:
email: mshalaby@live.ca

 
theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-architect


