title: Mohamad Shalaby
#description: Cayman is a clean, responsive theme for GitHub Pages.
#show_downloads: true
#google_analytics:

#theme: jekyll-theme-cayman
theme: jekyll-theme-dinky

header_pages:
  - [Contact](./index.html)  
  - [Research](./Research.html)
